### ISSUE TITLE
Should closures provided to iterator methods be fallible?

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-fallible-iterator#6]
The fallibility of `FallibleIterator`s isn't really exposed to many of the combinator methods. For example, `all` still takes a closure that simply returns a `bool`, where it could potentially return a `Result<bool, E>`. The `and_then` method is a version of `map` that takes a fallible closure, but it's the only instance of something like that in the current API.

It feels like it'll be pretty gross to have two copies of every combinator, one with a fallible closure and one without. Should all of them be fallible by default instead?

**Comment by sfackler** [comment]
@fitzgen do you have any thoughts here from your usage in gimli?

**Comment by fitzgen** [comment]
I don't have strong feelings either way. I guess ideally there would be two versions of each combinator, although I 100% see why you wouldn't want to write it out. I guess maybe there already are two versions, since the normal `Iterator` versions will work on the `Result`, right?

cc @philipc

**Comment by philipc** [comment]
We don't have many consumers of `FallibleIterator` in gimli, just implementers. I feel that fallible iterators should only be used for cases where the error prevents further iteration [1]. While an error in the closure could potentially prevent further iteration, I think that in general that's not going to be common. On the other hand, is making them all fallible going to be much of a burden for cases that don't need it?

This isn't specific to `FallibleIterator` either; if this is something that users need, then the same requirement would arise for closures provided to `Iterator` methods. I guess implementing something that could convert `Iterator<Item = T>` into `FallibleIterator<Item = T, Error = E>` would allow fallible closures to be used for `Iterator` too.

>I guess maybe there already are two versions, since the normal Iterator versions will work on the Result, right?

But if we want to use those for a `FallibleIterator` then that would require a way to lazily convert a `FallibleIterator` into an `Iterator`? I tried to come up with something that could do that but failed.

--
[1] and based on this criteria, some of our current implementations in gimli may be wrong, but I haven't checked

**Comment by jimblandy** [comment]
I would like the combinators to take fallible closures.

I'd like to use `FallibleIterator` to represent lazy streams of values in an interpreted language. The language has a 'filter' operation that invokes user code, and can fail. For now I just defined a `FallibleIteratorExt` trait that adds a `try_filter` method, but I think it would be a nice addition.

**Comment by jimblandy** [comment]
> This isn't specific to FallibleIterator either; if this is something that users need, then the same requirement would arise for closures provided to Iterator methods.

Right - I think the producer generating the sequence and the consumer applying adapters to it are almost separate questions:

- **Infallible producer, infallible adapters**: This is the `Iterator` case, which is clearly a popular success. Cases where `Item` is `Result<...>` seem questionable (it suggests intermittent, recoverable failure, which is not common), and they do arise in the I/O library, but this isn't the dominant case by far.

- **Fallible producer, fallible adapters**: This is what this issue is considering, and it's what I'd like. If the application area is one where production might fail, it seems natural that processing could fail too. The usual example is I/O, but in my case it's interpreting user code.

- **Fallible producer, infallible adapters**: This is today's `FallibleIterator`. Since infallible closures are so often adequate with `Iterator`, it makes sense that they would be adequate here. But given that the user has already escalated to `FallibleIterator`, it doesn't seem like much to ask to add `Ok` here and there.

- **Infallible producer, fallible adapters**: This is the last combination. This case could be supported with a variant of `fallible_iterator::convert` that builds a `FallibleIterator` from an `Iterator<Item=T>` as if by `convert(iter.map(Ok))`.

**Comment by jimblandy** [comment]
> It feels like it'll be pretty gross to have two copies of every combinator, one with a fallible closure and one without.

After talking with Nick, I wonder whether this is the right assumption to run with.

Above I argue that both fallible and infallible adapters have their place. The user's got to indicate which one they want somehow. Why not put a `try_` prefix on all the method names? `try_filter_map`?

**Comment by sfackler** [comment]
I mean, there is some cost to doubling the size of the crate, both with respect to API surface and raw source lines of code. I think I'm personally leaning towards fallible-everything. As you noted, it's not that big of a deal to stick a `Ok` in if your operation isn't actually fallible.

**Comment by jimblandy** [comment]
That suits me. That'd be a major version bump, then.

**Comment by jimblandy** [comment]
I've got this about halfway written [here][fc]. I started with the `try_` prefixes, but I'll take those out.

[fc]: https://github.com/jimblandy/rust-fallible-iterator/tree/fallible-closures

**Comment by jimblandy** [comment]
@sfackler This would make `map` and `and_then` synonyms. Would it be best to keep both, or drop `and_then`?

By the way: I do recognize that this is still an open discussion; "personally leaning towards" does not denote a settled decision. I'm just pressing ahead to see what it's like, and because it's handy for me at the moment.

**Comment by sfackler** [comment]
I think we'd want to keep the same terminology as Iterator, so we'd drop and_then.

It's great to have someone driving this forward! It had fallen off of my work queue for a while :)
